name: Publish package

on:
  push:
    branches:
      - main
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Get latest GitHub Actions code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set PAT in .npmrc
        run: |
          ls -al
          sed -i 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .npmrc
          echo "[SUCCESS] Personal access token replaced in .npmrc file"

      - name: Install Node.js dependencies
        run: npm ci # Clean Installation

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}